### ISSUE TITLE
I don't know how to run the code

### ISSUE THREAD

**Issue by universish** [scollovati/Aegis-decrypt#2]
I don't know how to edit the code.

example:

python3 aegis-decrypt.py --vault aegis-export-20221022-212146.json --entryname aegis_20221022.json --output json --password xxxxxxxxxxxxxx

is it ok?

but error:
No entries found

entry: unencrypted aegis output file name right?

**Comment by universish** [comment]
example:

python3 aegis-decrypt.py --vault aegis-export-20221022-212146_tutanota_dahil.json --entryname aegis_20221022.json --output json --password xxxxxxxxxxxxxx

is it ok?

**Comment by universish** [comment]
I am typing a 128 digit password that I created with bitwarden, which is complex and consists of different characters. part of the password sees the part of the password between two ! signs as an error, for password example: zzzzzzz!yyyyy!zzzzzzzzzz

python3 aegis-decrypt.py --vault aegis-export-20221022-212146.json --output json --password zzzzzzz!yyyyy!zzzzzzzzzz

bash: !yyyyy! : event not found

**Comment by urish** [comment]
you can enclose the password in single quotes, e.g.

```bash
python3 aegis-decrypt.py --vault aegis-export-20221022-212146.json --output json --password 'zzzzzzz!yyyyy!zzzzzzzzzz'
```
